/* Lived — public deployment settings.
   Copy to config.js for local development. In production, config.js is generated by
   .github/workflows/deploy.yml from GitHub Actions secrets (kept out of the repo and its logs).
   The deployed values are still visible to anyone who opens the site, so never put a real secret here:
   - GOOGLE_CLIENT_ID: OAuth 2.0 Client ID (type "Web application"). Public by design.
   - AI_ENDPOINT: URL of the deployed ai/worker.js. The AI key lives in the worker, not here. */
window.LIVED_CONFIG = {
  GOOGLE_CLIENT_ID: '',
  AI_ENDPOINT: ''
};
